config/routes.rb
Rails.application.routes.draw do
  root 'users#top'
  get'/about' => 'users#about'
  devise_for :users
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 100 }
  validates :opinion, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books
  validates :name, length: { in: 2 .. 20 }
  validates :intro,length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource) 
    user_path(resource)
  end
  def after_sign_out_path_for(resource)
    root_path
  end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@books = Book.page(params[:page]).per(5).order('created_at DESC')
		@new_book = Book.new
	end

	def show
		@book = Book.find(params[:id])
		@new_book = Book.new
	end

	def create
		@new_book = Book.new(book_params)
		@new_book.user_id = current_user.id
		if @new_book.save
			flash[:success] = "Posted successfully!"
			redirect_to user_path(current_user.id)
		else
			flash[:warning] = "Posted error."
			redirect_to books_path
		end
	end

		private

		def book_params
			params.require(:book).permit(:title, :opinion)
		end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).per(5).order('created_at DESC')
    @new_book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @new_book = Book.new
    @books = Book.where(user_id: @user.id)
    @books = @books.page(params[:page]).per(5).order('created_at DESC')
  end

  def edit
    @edit_user = User.find(params[:id])
    if @edit_user == current_user
    else
      redirect_to users_path
    end
  end
  
  def update
    edit_user = User.find(params[:id])
    if edit_user.update(user_params)
      flash[:success] = "Changed profile successfully!"
      redirect_to user_path(edit_user.id)
    else
      flash[:warning] = "Changed profile error."
      redirect_to edit_user_path(edit_user.id)
    end
  end  
  
    private

    def user_params
      params.require(:user).permit(:name, :profile_image, :intro)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <%= msg %>
      </div>
    <% end %>
  <div class="row">
    <div class="col-3">
      <%= render '../views/sidebar', user: current_user, new_book: @new_book %>
    </div>
    <div class="col-9">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= book.user.id %></td>
            <td><%= link_to "#{book.title}", book_path(book.id)%></td>
            <td><%= book.opinion %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render '../views/sidebar', user: @book.user, new_book: @new_book %>
    </div>
    <div class="col-9">
      <h2>Book detail</h2>
      <table class="table table-hover">
        <tbody>
          <tr>
            <td>
              <a href="/users/<%= @book.user.id %>">
              <% if @book.user.profile_image.nil? %>
                <%= image_tag scr = "no_image.jpg", :size=>"50x50" %>
              <% else %>
                <%= image_tag attachment_url(@book.user, :profile_image, :fill, 50, 50, format: "jpg") %>
              <% end %><br>
              <%= @book.user.name %>
              </a>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.opinion %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/books">Bookers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/users/<%= current_user.id %>">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/books">Books</a>
            </li>
            <li class="nav-item">
              <form method="delete" action="/">
                <a class="nav-link" data-method="delete" href="/users/sign_out">Log out</a>
              </form>
            </li>
          </ul>
        </div>
      </nav>
    <% else %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/books">Bookers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_up">Sign up</a>
            </li>
              <a class="nav-link" href="/users/sign_in">Log in</a>
          </ul>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h2>What's Bookers?</h2>
      <p>
        "Bookers"とは DMM WEBCAMP のコンテンツ課題である。
      </p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 offset-4">
      <h2>User info</h2>

      <% @edit_user.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>

      <%= form_with(model: @edit_user, local: true) do |f| %>
        <% if @edit_user.errors.any? %>
          <div id="error_explanation">
          <h2><%= pluralize(@edit_user.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
              <% @edit_user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "col-12"%>
        </div>

        <div class="field">
          <%= f.label :profile_image %><br>
          <%= f.attachment_field :profile_image, class: "col-12"%>
        </div>

        <div class="field">
          <%= f.label :intro %><br>
          <%= f.text_area :intro, class: "col-12"%>
        </div>
        <br>
        <div class="actions">
          <%= f.submit 'Update User', class: "btn btn-primary col-12"%>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render '../views/sidebar', user: current_user, new_book: @new_book %>
    </div>
    <div class="col-9">
      <h2>Users</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <% if user.profile_image.nil? %>
                <%= image_tag scr = "no_image.jpg", :size=>"50x50" %>
              <% else %>
                <%= image_tag attachment_url(user, :profile_image, :fill, 50, 50, format: "jpg") %>
              <% end %>
            </td>
            <th><%= user.name %></td>
            <td><%= link_to "show", user_path(user.id)%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <%= msg %>
      </div>
    <% end %>
  <div class="row">
    <div class="col-3">
      <%= render '../views/sidebar', user: @user, new_book: @new_book %>
    </div>
    <div class="col-9">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <% if book.user.profile_image.nil? %>
                <%= image_tag scr = "no_image.jpg", :size=>"50x50" %>
              <% else %>
                <%= image_tag attachment_url(book.user, :profile_image, :fill, 50, 50, format: "jpg") %>
              <% end %>
            </td>
            <td><%= link_to "#{book.title}", book_path(book.id)%></td>
            <td><%= book.opinion %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @books %>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
          <%= msg %>
        </div>
      <% end %>
      <h2>Welcome to Bookers!!</h2>
      <p>
        In Bookers,<br>
        you can share and exchange your opinions, inpressions, and emotions<br>
        about varioius books!
      </p>
      <div class="btn-group-vertical col-12">
        <a class="btn btn-outline-info" href="/users/sign_in">Log in</a>
        <a class="btn btn-outline-success" href="/users/sign_up">Sign up</a>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
</script>